# Generated by Django 2.2.9 on 2020-03-10 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20200307_1956'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='image_fun',
            new_name='image',
        ),
    ]
